#!/bin/bash 

# Install Appimages 
# Gearlever and AppImageLauncher both manage appimages. Both have a cli for scripts.  
# Try AppImageLauncher first.  
# Download appimages 
# Put them in ~/bin/appimages, but need to check for existance  of # ~/bin, and if it doesn't exist, create it.
# Also, check for the file's existance before downloading it.
#


DIRECTORY="/home/john/bin/appimages"
if [ ! -d "$DIRECTORY" ]; then
	mkdir "$DIRECTORY"
fi

# wget -qO ~/bin/appimages/nextcloud-desktop.appimage "https://github.com/nextcloud-releases/desktop/releases/download/v4.0.1/Nextcloud-4.0.1-x86_64.AppImage"

curl -s https://api.github.com/repos/nextcloud-releases/desktop/releases/latest \
| grep 'browser_download_url.*AppImage"' \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i - -P $DIRECTORY
 

# Next setup the symlink between the nextcloud sync folder and the local documents folder. This is done in the
# fstab folder.
